#!/bin/sh
#ssh root@168.181.187.26 -p 5234 <<EOF
# cd ~/node-app
# git pull
# pm2 restart all
# exit
#EOF

ssh root@168.181.187.26 -p 5234 "cd /var/www/jenkins/test"
ssh root@168.181.187.26 -p 5234 "git pull origin main"